#!/usr/bin/python

import _logging
import importlib
import pathlib
from _functions import *

_logging.output( 'Media-Hub v2.0 Built Time: ' + mh_built_date().decode() +
        ", " + mh_built_time().decode() )

casesPath   =   pathlib.Path( './cases' )

cases   =   list( casesPath.glob( '*.py' ))

i   =   0
for c in cases:
    print( '[' + str( i ) + ']\t' + c.name )
    i   +=  1

index  =   input( 'Please input the test case index[ e.g., 0 for ' + cases[0].name + ' ]:\n' )

case   =   importlib.import_module( 'cases.' + cases[ int( index )].stem )
case.run()
