/*
 * Generated by plugin-codegen.
 */
#ifndef __MH_DEV_IAP1_H__
#define __MH_DEV_IAP1_H__

#include <gio/gio.h>
#include <mh_dev.h>

/*
 * Type Macros
 */

#define MH_TYPE_DEV_IAP1 \
	(mh_dev_iap1_get_type())
#define MH_DEV_IAP1(obj) \
	(G_TYPE_CHECK_INSTANCE_CAST((obj), MH_TYPE_DEV_IAP1, MHDevIap1))
#define MH_IS_DEV_IAP1(obj) \
	(G_TYPE_CHECK_INSTANCE_TYPE((obj), MH_TYPE_DEV_IAP1))
#define MH_DEV_IAP1_CLASS(klass) \
	(G_TYPE_CHECK_CLASS_CAST((klass), MH_TYPE_DEV_IAP1, MHDevIap1Class))
#define MH_IS_DEV_IAP1_CLASS(klass) \
	(G_TYPE_CHECK_CLASS_TYPE((klass), MH_TYPE_DEV_IAP1))
#define MH_DEV_IAP1_GET_CLASS(obj) \
	(G_TYPE_INSTANCE_GET_CLASS((obj), MH_TYPE_DEV_IAP1, MHDevIap1Class))

typedef struct _MHDevIap1		MHDevIap1;
typedef struct _MHDevIap1Class	MHDevIap1Class;

struct _MHDevIap1Class
{
	MHDevClass parent_class;

	/* Class Ios */

	/* Class Methods */

	/* Class Properties */
};

struct _MHDevIap1
{
	MHDev parent;

	gint (* read)( guint8 **, gint len );
	gint (* write)( guint8 *, gint len );
	gint (* read_ea)( guint8 **, gint len );
	gint (* write_ea)( guint8 *, gint len );

	/* Instance Members */
	gint64 deviceId;
};

/* used by MH_TYPE_DEV_IAP1 */
GType mh_dev_iap1_get_type( void );

/* Ios List */

#endif /* __MH_DEV_IAP1_H__ */
