/*
 * Generated by object-codegen.
 */
#include <glib.h>
#include "dev_iap1.h"
#include <mh_core.h>
#include <mh_contents.h>
#include <mh_misc.h>
#include <mh_playlist.h>

typedef struct _MHDevIap1Private MHDevIap1Private;

struct _MHDevIap1Private
{
	gint dummy;
};

G_DEFINE_TYPE_WITH_PRIVATE( MHDevIap1, mh_dev_iap1, MH_TYPE_DEV )

//
//enum {
//	/* Ios */
//
//	/* Signals */
//
//	N_SIGNALS
//};
//
//static guint signals[ N_SIGNALS ] = {0};

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _play_by_list
 *  Description:
 * =====================================================================================
 */
static void _play_by_list( MHDev * self, MHPb * pb, MHPlaylist * playlist )
{
}      /* -----  end of static function _play_by_list  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _stop
 *  Description:
 * =====================================================================================
 */
static void _stop( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _stop  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _play
 *  Description:
 * =====================================================================================
 */
static void _play( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _play  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _pause
 *  Description:
 * =====================================================================================
 */
static void _pause( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _pause  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _play_pause
 *  Description:
 * =====================================================================================
 */
static void _play_pause( MHDev * self )
{
}      /* -----  end of static function _play_pause  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _resume
 *  Description:
 * =====================================================================================
 */
static void _resume( MHDev * self )
{
}      /* -----  end of static function _resume  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _forward
 *  Description:
 * =====================================================================================
 */
static void _forward( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _forward  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _forward_done
 *  Description:
 * =====================================================================================
 */
static void _forward_done( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _forward_done  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _backward
 *  Description:
 * =====================================================================================
 */
static void _backward( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _backward  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _backward_done
 *  Description:
 * =====================================================================================
 */
static void _backward_done( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _backward_done  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_index
 *  Description:
 * =====================================================================================
 */
static void _set_index( MHDev * self, MHPb * pb, uint32_t index ) 
{
}      /* -----  end of static function _set_index  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_speed
 *  Description:
 * =====================================================================================
 */
static void _set_speed( MHDev * self, guint speed )
{
}      /* -----  end of static function _set_speed  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_repeat
 *  Description:
 * =====================================================================================
 */
static void _set_repeat( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _set_repeat  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_shuffle
 *  Description:
 * =====================================================================================
 */
static void _set_shuffle( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _set_shuffle  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_buffer_time
 *  Description:
 * =====================================================================================
 */
static void _set_buffer_time( MHDev * self )
{
}      /* -----  end of static function _set_buffer_time  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _start_scan
 *  Description:
 * =====================================================================================
 */
static void _start_scan( MHDev * self, MHDevScanType type)
{
}      /* -----  end of static function _start_scan  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _register_scan_callback
 *  Description:  
 * =====================================================================================
 */
static uint32_t  _register_events_listener(MHDev * self, MHDevEventsListener * listener)
{
	return 0;
}		/* -----  end of static function _register_scan_callback  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _previous
 *  Description:
 * =====================================================================================
 */
static void _previous( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _previous  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _next
 *  Description:
 * =====================================================================================
 */
static void _next( MHDev * self, MHPb * pb )
{
}      /* -----  end of static function _next  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _register_pb_events_listener
 *  Description:  
 * =====================================================================================
 */
static gboolean _register_pb_events_listener( MHDev * self, MHPb * pb, MHDevPbEventsListener * listener )
{
	return TRUE;
}		/* -----  end of static function _register_pb_events_listener  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _dispose
 *  Description:
 * =====================================================================================
 */
static void _dispose( GObject * object )
{
	MHDevIap1 * _self	=	MH_DEV_IAP1( object );

	G_OBJECT_CLASS( mh_dev_iap1_parent_class )->dispose( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _finalize
 *  Description:
 * =====================================================================================
 */
static void _finalize( GObject * object )
{
	MHDevIap1 * _self	=	MH_DEV_IAP1( object );
	MHDevIap1Private * _priv	=	mh_dev_iap1_get_instance_private( _self );

	G_OBJECT_CLASS( mh_dev_iap1_parent_class )->finalize( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_iap1_init
 *  Description:
 * =====================================================================================
 */
static void mh_dev_iap1_init( MHDevIap1 * self )
{
	MHDevIap1Private * _priv	=	mh_dev_iap1_get_instance_private( self );
	MHDev * _dev	=	MH_DEV( self );

	_dev->type	=	"iap1";
	g_message("mh_dev_iap1_init attach iap1 ");
	mh_core_attach_dev( _dev );
}       /* -----  end of static function mh_dev_iap1_init  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_iap1_class_init
 *  Description:
 * =====================================================================================
 */
static void mh_dev_iap1_class_init( MHDevIap1Class * klass )
{
	MHDevClass * _parentClass	=	MH_DEV_CLASS( klass );
	GObjectClass * _gobjectClass	=	G_OBJECT_CLASS( klass );

	_gobjectClass->dispose	=	_dispose;
	_gobjectClass->finalize	=	_finalize;

	/* assemble ios of mh_dev_iap1 class */

	/* assemble methods of mh_dev_iap1 class */
	_parentClass->play_by_list	=	_play_by_list;
	_parentClass->stop	=	_stop;
	_parentClass->play	=	_play;
	_parentClass->pause	=	_pause;
	_parentClass->play_pause	=	_play_pause;
	_parentClass->resume	=	_resume;
	_parentClass->forward	=	_forward;
	_parentClass->forward_done	=	_forward_done;
	_parentClass->backward	=	_backward;
	_parentClass->backward_done	=	_backward_done;
	_parentClass->set_index	=	_set_index;
	_parentClass->set_speed	=	_set_speed;
	_parentClass->set_repeat	=	_set_repeat;
	_parentClass->set_shuffle	=	_set_shuffle;
	_parentClass->set_buffer_time	=	_set_buffer_time;
	_parentClass->start_scan	=	_start_scan;
	_parentClass->next	=	_next;
	_parentClass->previous	=	_previous;

	_parentClass->register_events_listener	=	_register_events_listener;

	/* Ios */
	/* Signals */
}       /* -----  end of static function mh_dev_iap1_class_init  ----- */

