#!/usr/bin/python

import sys
import argparse

import _parser
import _codegen

def codegen_main():
	arg_parser	=	argparse.ArgumentParser( description = 'Media-Hub Plugin Source Code Generating Tool' )
	arg_parser.add_argument( '--xml-file', metavar = 'FILE', required = False, default = "MHObjects.xml",
			help = 'Media-Hub Plugin introspection XML file' )

	args	=	arg_parser.parse_args()

	print( 'Loading ' + args.xml_file + '...' )
	f	=	open( args.xml_file )
	xml_data	=	f.read()
	f.close()

	print( 'Parsing ' + args.xml_file + '...' )
	parsed_klasses	=	_parser.parse_plugin_xml( xml_data )

	print( 'Generating Source Codes ...' )
	for klass in parsed_klasses:
		klass.post_process()
		_codegen.CodeGenerator( klass ).generate()

	print( 'Done.' )

if __name__ == "__main__":
	codegen_main()
