/*
 * Generated by plugin-codegen.
 */
#include <mh_io.h>

typedef struct _MHIoPrivate MHIoPrivate;

struct _MHIoPrivate
{
	GType type;

	GMainContext * context;
	GMainLoop * mainloop;
	GThread * thread;
};

G_DEFINE_TYPE_WITH_PRIVATE( MHIo, mh_io, G_TYPE_OBJECT )

typedef struct _IOSyncData 
{
	GTask * task;
	GMainContext * context;
	GMainLoop * loop;
} IOSyncData;				/* ----------  end of struct IOSyncData  ---------- */

typedef struct _IOData 
{
	MHIo * self;
	gchar * method_name;
	GVariant * parameters;
} IOData;				/* ----------  end of struct IOData  ---------- */

typedef enum _MHIoProperty
{
	PROP_0,

	PROP_IO_NAME,

	N_PROPERTIES
} MHIoProperty;				/* ----------  end of enum MHIoProperty  ---------- */

static GParamSpec * io_properties[ N_PROPERTIES ] = { NULL };

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  io_thread
 *  Description:  
 * =====================================================================================
 */
static gpointer io_thread ( const gpointer user_data )
{
	MHIoPrivate * _priv	=	mh_io_get_instance_private( MH_IO( user_data ));

	g_main_context_push_thread_default( _priv->context );

	g_main_loop_run( _priv->mainloop );

	return NULL;
}		/* -----  end of static function io_thread  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _quit
 *  Description:  
 * =====================================================================================
 */
static gboolean _quit( gpointer user_data )
{
	GMainLoop * _mainloop	=	( GMainLoop * )user_data;

	g_main_loop_quit( _mainloop );

	return G_SOURCE_REMOVE;
}		/* -----  end of static function _quit  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _dispose
 *  Description:
 * =====================================================================================
 */
static void _dispose( GObject * object )
{
	MHIo * _self	=	MH_IO( object );
	MHIoPrivate * _priv	=	mh_io_get_instance_private( _self );
	GSource * _source	=	g_idle_source_new();

	g_source_set_callback( _source, _quit, _priv->mainloop, NULL );

	g_source_attach( _source, _priv->context );

	g_source_unref( _source );

	if( g_thread_self() != _priv->thread )
		g_thread_join( _priv->thread );

	g_main_loop_unref( _priv->mainloop );
	g_main_context_unref( _priv->context );

	G_OBJECT_CLASS( mh_io_parent_class )->dispose( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _finalize
 *  Description:
 * =====================================================================================
 */
static void _finalize( GObject * object )
{
	MHIo * _self	=	MH_IO( object );
	MHIoPrivate * _priv	=	mh_io_get_instance_private( _self );

	G_OBJECT_CLASS( mh_io_parent_class )->finalize( object );
}

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_dispatch
 *  Description:  
 * =====================================================================================
 */
void mh_io_dispatch ( MHIo * self, GSource * source )
{
	MHIoPrivate * _priv	=	mh_io_get_instance_private( self );

	g_source_attach( source, _priv->context );
}		/* -----  end of function mh_io_dispatch  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_init
 *  Description:
 * =====================================================================================
 */
static void mh_io_init( MHIo * self )
{
	MHIoPrivate * _priv	=	NULL;

	_priv	=	mh_io_get_instance_private( self );
	
	_priv->context	=	g_main_context_new();
	_priv->mainloop	=	g_main_loop_new( _priv->context, FALSE );
}       /* -----  end of static function mh_io_init  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_get_property
 *  Description:  
 * =====================================================================================
 */
static void mh_io_get_property( GObject * object, guint property_id, GValue * value,
		GParamSpec * spec)
{
}		/* -----  end of static function mh_io_get_property  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_set_property
 *  Description:  
 * =====================================================================================
 */
static void mh_io_set_property( GObject * object, guint property_id, const GValue * value,
		GParamSpec * spec)
{
}		/* -----  end of static function mh_io_set_property  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_constructor
 *  Description:  
 * =====================================================================================
 */
static GObject * mh_io_constructor( GType type, guint n_construct_params, 
									GObjectConstructParam * construct_params )
{
	GObject * _obj;
	const gchar * _ioName	=	NULL;
	int32_t i;
	MHIoPrivate * _priv	=	NULL;

	_obj	=	G_OBJECT_CLASS( mh_io_parent_class )->constructor( type, 
			n_construct_params, construct_params );

	_priv	=	mh_io_get_instance_private( MH_IO( _obj ));

	_priv->type		=	type;

	for( i = 0; i < n_construct_params; i ++ )
	{
		if( construct_params[i].pspec == io_properties[ PROP_IO_NAME ] )
		{
			_ioName	=	g_value_get_string( construct_params[i].value );

			break;
		}
	}

	_priv->thread	=	g_thread_new( _ioName, io_thread, _obj );

	return _obj;
}		/* -----  end of static function mh_io_constructor  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_class_init
 *  Description:
 * =====================================================================================
 */
static void mh_io_class_init( MHIoClass * klass )
{
	GObjectClass * _gobjectClass	=	G_OBJECT_CLASS( klass );

	_gobjectClass->constructor	=	mh_io_constructor;
	_gobjectClass->set_property	=	mh_io_set_property;
	_gobjectClass->get_property	=	mh_io_get_property;
	_gobjectClass->dispose		=	_dispose;
	_gobjectClass->finalize		=	_finalize;

	io_properties[ PROP_IO_NAME ]	=	
		g_param_spec_string( "io-name", "MHIo property", "Set io thread's name",
				"io-name not set", G_PARAM_CONSTRUCT_ONLY | G_PARAM_READWRITE );

	g_object_class_install_properties( _gobjectClass, N_PROPERTIES, io_properties );
}       /* -----  end of static function mh_io_class_init  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  io_invoke_cb
 *  Description:  
 * =====================================================================================
 */
static void io_invoke_cb ( MHIo * self, GTask * task, gpointer user_data )
{
	IOSyncData * _data	=	(IOSyncData *)user_data;

	_data->task	=	g_object_ref( task );

	g_main_loop_quit( _data->loop );
}		/* -----  end of static function io_invoke_cb  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_invoke_sync
 *  Description:  
 * =====================================================================================
 */
GVariant * mh_io_invoke_sync( MHIo * self, const gchar * method_name, GVariant * parameters,
		GCancellable * cancellable, GError ** error )
{
	IOSyncData _data;
	GVariant * _ret;

	_data.context	=	g_main_context_ref_thread_default();
	_data.loop		=	g_main_loop_new( _data.context, FALSE );

	mh_io_invoke( self, method_name, parameters, cancellable, (GAsyncReadyCallback)io_invoke_cb, &_data );

	g_main_loop_run( _data.loop );

	_ret	=	mh_io_invoke_finish( self, _data.task, error );

	g_main_loop_unref( _data.loop );
	g_main_context_unref ( _data.context );
	g_object_unref( _data.task );

	return _ret;
}		/* -----  end of function mh_io_invoke_sync  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  io_source_cb
 *  Description:  
 * =====================================================================================
 */
static gboolean io_source_cb ( gpointer user_data )
{
	GTask * _task	=	(GTask *)user_data;
	IOData * _data	=	g_task_get_task_data( _task );
	GVariantIter _iter;
	GVariant * _child;
	GValue * _paramv, _retval	=	G_VALUE_INIT;
	guint _sig;
//	MHIoPrivate * _priv	=	mh_io_get_instance_private( _data->self );

//	_sig	=	g_signal_lookup( _data->method_name, _priv->type );
	_sig	=	g_signal_lookup( _data->method_name, (( GTypeInstance * )_data->self )->g_class->g_type );
	g_message( "%s %d", __func__, __LINE__ );

	if( _sig > 0 )
	{
		gint _paramn	=	g_variant_n_children( _data->parameters );
		gint _offset	=	2, i;

		_paramv	=	g_new0( GValue, _paramn + 2 );

		g_value_init( _paramv + 0, MH_TYPE_IO );
		g_value_set_object( _paramv + 0, _data->self );
		g_value_init( _paramv + 1, G_TYPE_TASK );
		g_value_set_object( _paramv + 1, _task );

		g_variant_iter_init( &_iter, _data->parameters );

		while( (_child = g_variant_iter_next_value( &_iter )) != NULL)
		{
			g_dbus_gvariant_to_gvalue( _child, _paramv + _offset );

			_offset	++;

			g_variant_unref( _child );
		}

		g_value_init( &_retval, G_TYPE_BOOLEAN );
		g_signal_emitv( _paramv, _sig, 0, &_retval );

		if( !g_value_get_boolean( &_retval ))
		{
			GError * _error	=	g_error_new( g_quark_from_string( "mh_io" ), -MH_IO_GENERIC_ERROR, 
					"Unknown error occured on calling method [%s] of [%p]", _data->method_name, _data->self );
			g_task_return_error( _task, _error );
		}

		g_value_unset( &_retval );

		for( i = 0; i < _paramn + 2; i ++)
		{
			g_value_unset( _paramv + i );
		}

		g_free( _paramv );
	}
	else
	{
		GError * _error	=	g_error_new( g_quark_from_string( "mh_io" ), -MH_IO_METHOD_ERROR, 
				"Method [%s] of [%p] doesn't exist", _data->method_name, _data->self );
		g_task_return_error( _task, _error );
	}

	return G_SOURCE_REMOVE;
}		/* -----  end of static function io_source_cb  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  io_release_data
 *  Description:  
 * =====================================================================================
 */
static void io_release_data ( IOData * data )
{
	g_object_unref( data->self );
	g_free( data->method_name );
	g_variant_unref( data->parameters );
	g_slice_free( IOData, data );
}		/* -----  end of static function io_release_data  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_invoke
 *  Description:  
 * =====================================================================================
 */
void mh_io_invoke( MHIo * self, const gchar * method_name, GVariant * parameters,
		GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data )
{
	GSource * _source	=	NULL;
	GTask * _task		=	g_task_new( self, cancellable, callback, user_data );
	IOData * _data		=	g_slice_new( IOData );
	MHIoPrivate * _priv	=	mh_io_get_instance_private( _data->self );

	_data->self			=	g_object_ref( self );
	_data->method_name	=	g_strdup( method_name );
	_data->parameters	=	g_variant_ref_sink( parameters );

	g_task_set_task_data( _task, _data, (GDestroyNotify)io_release_data );

	_source	=	g_idle_source_new();

	g_source_set_callback( _source, io_source_cb, _task, (GDestroyNotify)g_object_unref );

	g_source_attach( _source, _priv->context );

	g_source_unref( _source );
}		/* -----  end of function mh_io_invoke  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_invoke_finish
 *  Description:  
 * =====================================================================================
 */
GVariant * mh_io_invoke_finish( MHIo * self, GTask * task, GError ** error )
{
	return g_task_propagate_pointer( task, error );
}		/* -----  end of function mh_io_invoke_finish  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_io_invoke_return_value
 *  Description:  
 * =====================================================================================
 */
void mh_io_invoke_return_value( GTask * task, GVariant * result )
{
	g_task_return_pointer( task, g_variant_ref_sink( result ), (GDestroyNotify)g_variant_unref );
}		/* -----  end of function mh_io_invoke_return_value  ----- */
