/*
 * Generated by object-codegen.
 */
#include <glib.h>
#include <mh_music.h>

typedef struct _MHMusicPrivate MHMusicPrivate;

struct _MHMusicPrivate
{
	gint dummy;
};

G_DEFINE_TYPE_WITH_PRIVATE( MHMusic, mh_music, MH_TYPE_ITEM )

enum
{
	PROP_0,

	PROP_MUSIC_TITLE,
	PROP_MUSIC_RATING,
	PROP_MUSIC_DURATION,
	PROP_MUSIC_ALBUM_TITLE,
	PROP_MUSIC_TRACK,
	PROP_MUSIC_TRACK_COUNT,
	PROP_MUSIC_DISC,
	PROP_MUSIC_DISC_COUNT,
	PROP_MUSIC_ARTIST,
	PROP_MUSIC_ALBUM_ARTIST,
	PROP_MUSIC_GENRE,
	PROP_MUSIC_COMPOSER,

	N_PROPERTIES
};

static GParamSpec *musicProperties[ N_PROPERTIES ] = { NULL, };

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_music_get_property
 *  Description:  
 * =====================================================================================
 */
static void mh_music_get_property( GObject * object, guint property_id, GValue * value,
		GParamSpec * spec)
{
	MHMusic * _self	=	MH_MUSIC( object );

	switch( property_id )
	{
	case PROP_MUSIC_TITLE:
		g_value_set_string( value, _self->title );
		break;
	case PROP_MUSIC_RATING:
		g_value_set_uint( value, _self->rating );
		break;
	case PROP_MUSIC_DURATION:
		g_value_set_uint64( value, _self->duration );
		break;
	case PROP_MUSIC_ALBUM_TITLE:
		g_value_set_string( value, _self->album_title );
		break;
	case PROP_MUSIC_TRACK:
		g_value_set_uint( value, _self->track );
		break;
	case PROP_MUSIC_TRACK_COUNT:
		g_value_set_uint( value, _self->track_count );
		break;
	case PROP_MUSIC_DISC:
		g_value_set_uint( value, _self->disc );
		break;
	case PROP_MUSIC_DISC_COUNT:
		g_value_set_uint( value, _self->disc_count );
		break;
	case PROP_MUSIC_ARTIST:
		g_value_set_string( value, _self->artist );
		break;
	case PROP_MUSIC_ALBUM_ARTIST:
		g_value_set_string( value, _self->album_artist );
		break;
	case PROP_MUSIC_GENRE:
		g_value_set_string( value, _self->genre );
		break;
	case PROP_MUSIC_COMPOSER:
		g_value_set_string( value, _self->composer );
		break;
	default:
		break;
	}
}		/* -----  end of static function mh_music_get_property  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_music_set_property
 *  Description:  
 * =====================================================================================
 */
static void mh_music_set_property( GObject * object, guint property_id, const GValue * value,
		GParamSpec * spec)
{
	MHMusic * _self	=	MH_MUSIC( object );

	switch( property_id )
	{
	case PROP_MUSIC_TITLE:
		g_strlcpy( _self->title, g_value_get_string( value ), MH_STRING_LONG );
		break;
	case PROP_MUSIC_RATING:
		_self->rating	=	g_value_get_uint( value );
		break;
	case PROP_MUSIC_DURATION:
		_self->duration	=	g_value_get_uint64( value );
		break;
	case PROP_MUSIC_ALBUM_TITLE:
		g_strlcpy( _self->album_title, g_value_get_string( value ), MH_STRING_LONG );
		break;
	case PROP_MUSIC_TRACK:
		_self->track	=	g_value_get_uint( value );
		break;
	case PROP_MUSIC_TRACK_COUNT:
		_self->track_count	=	g_value_get_uint( value );
		break;
	case PROP_MUSIC_DISC:
		_self->disc	=	g_value_get_uint( value );
		break;
	case PROP_MUSIC_DISC_COUNT:
		_self->disc_count	=	g_value_get_uint( value );
		break;
	case PROP_MUSIC_ARTIST:
		g_strlcpy( _self->artist, g_value_get_string( value ), MH_STRING_LONG );
		break;
	case PROP_MUSIC_ALBUM_ARTIST:
		g_strlcpy( _self->album_artist, g_value_get_string( value ), MH_STRING_LONG );
		break;
	case PROP_MUSIC_GENRE:
		g_strlcpy( _self->genre, g_value_get_string( value ), MH_STRING_LONG );
		break;
	case PROP_MUSIC_COMPOSER:
		g_strlcpy( _self->composer, g_value_get_string( value ), MH_STRING_LONG );
		break;
	default:
		break;
	}
}		/* -----  end of static function mh_music_set_property  ----- */


/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _dispose
 *  Description:
 * =====================================================================================
 */
static void _dispose( GObject * object )
{
//	g_message("music.c:dispose");
	G_OBJECT_CLASS( mh_music_parent_class )->dispose( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _finalize
 *  Description:
 * =====================================================================================
 */
static void _finalize( GObject * object )
{
//	g_message("music.c:finalize");
	MHMusic * _self	=	MH_MUSIC( object );
	if (_self->title !=	NULL )
	{
		g_free( _self->title );
	}
	if (_self->album_title !=	NULL )
	{
		g_free( _self->album_title );
	}
	if (_self->artist !=	NULL )
	{
		g_free( _self->artist );
	}
	if (_self->album_artist !=	NULL )
	{
		g_free( _self->album_artist );
	}
	if (_self->genre !=	NULL )
	{
		g_free( _self->genre );
	}
	if (_self->composer !=	NULL )
	{
		g_free( _self->composer );
	}

	G_OBJECT_CLASS( mh_music_parent_class )->finalize( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_music_init
 *  Description:
 * =====================================================================================
 */
static void mh_music_init( MHMusic * self )
{
	self->title =	NULL;
	self->album_title =	NULL;
	self->artist =	NULL;
	self->album_artist =	NULL;
	self->genre =	NULL;
	self->composer =	NULL;
	self->mediaType	=	MH_MEDIA_MUSIC;
	self->album_compliation	=	false;
	MH_ITEM( self )->type	=	MH_ITEM_MUSIC;
	MH_ITEM( self )->valid	=	MH_ITEM_UNKNOWN;
	self->last_chgtime = 0;

}       /* -----  end of static function mh_music_init  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_music_class_init
 *  Description:
 * =====================================================================================
 */
static void mh_music_class_init( MHMusicClass * klass )
{
	MHMusicClass * _parentClass	=	MH_MUSIC_CLASS( klass );
	GObjectClass * _gobjectClass	=	G_OBJECT_CLASS( klass );

	_gobjectClass->dispose	=	_dispose;
	_gobjectClass->finalize	=	_finalize;
	_gobjectClass->set_property	=	mh_music_set_property;
	_gobjectClass->get_property	=	mh_music_get_property;

	musicProperties[ PROP_MUSIC_TITLE ]	=	
		g_param_spec_string( "title", "MHMusic property", "Title of music item",
				"", G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_RATING ]	=	
		g_param_spec_uint( "rating", "MHMusic property", "Rating of music item",
				0, G_MAXUINT, 0, G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_DURATION ]	=	
		g_param_spec_uint64( "duration", "MHMusic property", "Duration of music item",
				0, G_MAXUINT64, 0, G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_ALBUM_TITLE ]	=	
		g_param_spec_string( "album-title", "MHMusic property", "Album title of music item",
				"", G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_TRACK ]	=	
		g_param_spec_uint( "track", "MHMusic property", "Track of music item",
				0, G_MAXUINT, 0, G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_TRACK_COUNT ]	=	
		g_param_spec_uint( "track-count", "MHMusic property", "Track count of music item",
				0, G_MAXUINT, 0,  G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_DISC ]	=	
		g_param_spec_uint( "disc", "MHMusic property", "Disc of music item",
				0, G_MAXUINT, 0, G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_DISC_COUNT ]	=	
		g_param_spec_uint( "disc-count", "MHMusic property", "Disc count of music item",
				0, G_MAXUINT, 0, G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_ARTIST ]	=	
		g_param_spec_string( "artist", "MHMusic property", "Artist title of music item",
				"", G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_ALBUM_ARTIST ]	=	
		g_param_spec_string( "album-artist", "MHMusic property", "Album artist of music item",
				"", G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_GENRE ]	=	
		g_param_spec_string( "genre", "MHMusic property", "Genre of music item",
				"", G_PARAM_READABLE );

	musicProperties[ PROP_MUSIC_COMPOSER ]	=	
		g_param_spec_string( "composer", "MHMusic property", "Composer of music item",
				"", G_PARAM_READABLE );

	g_object_class_install_properties( _gobjectClass, N_PROPERTIES, musicProperties );
	/* assemble ios of mh_music class */

	/* assemble methods of mh_music class */

	/* Ios */
	/* Signals */
}       /* -----  end of static function mh_music_class_init  ----- */

