/*
 * Generated by object-codegen.
 */
#include <glib.h>
#include "pause.h"
#include "stmdefs.h"
#include "switching.h"
#include "seeking.h"
#include <mh_playlist.h>
#include <mh_dev.h>
#include <mh_pb.h>
typedef struct _MHStatePausePrivate MHStatePausePrivate;

struct _MHStatePausePrivate
{
	gint dummy;
};

G_DEFINE_TYPE_WITH_PRIVATE( MHStatePause, mh_state_pause, MH_TYPE_STATE )

static GObject * pauseObject;
/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _action
 *  Description:
 * =====================================================================================
 */
static void _action( MHState * self, MHPb * pb, guint event, gpointer param1, gpointer param2 )
{
	MHPb * _pb = MH_PB( pb );
	switch( event )
	{
		case EVENT_PLAY:
			g_message( "[Pause] to [Playing]" );
			if(( _pb->mhDev	!=	NULL ) && ( g_strcmp0( _pb->mhDev->type , "iap2")!=0 ))
			{
				mh_pb_dispatch( _pb, EVENT_CHANGE, GUINT_TO_POINTER( PLAY_STATUS ), NULL );
			}
			mh_dev_play( _pb->mhDev, _pb );
			break;
		case EVENT_SWITCHING_NEXT:
			g_message( "[Pause] to [switching]" );
			mh_pb_dispatch( _pb, EVENT_CHANGE, GUINT_TO_POINTER( SWITCHING_STATUS ), NULL );
			mh_dev_next( _pb->mhDev, _pb );
			break;
		case EVENT_SWITCHING_PREVIOUS:
			g_message( "[Pause] to [switching]" );
			mh_pb_dispatch( _pb, EVENT_CHANGE, GUINT_TO_POINTER( SWITCHING_STATUS ), NULL );
			mh_dev_previous( _pb->mhDev, _pb );
			break;
		case EVENT_SWITCHING_SELECT:
			g_message( "[Pause] to [switching]" );
			if( _pb->playlist != NULL )
			{
				mh_dev_set_index( _pb->mhDev, _pb, ( uint32_t )_pb->playlist->index );
			}else{
				g_message("pause %s playlist is NULL!!",__func__);		
			}
			break;
		case EVENT_SEEKING:
			g_message( "[Pause] to [seeking]" );	
			mh_pb_dispatch( _pb, EVENT_CHANGE, GUINT_TO_POINTER( SEEKING_STATUS ), GUINT_TO_POINTER( PAUSE_STATUS ) );
			mh_dev_seek( _pb->mhDev, _pb, ( uint32_t )_pb->seeking_pos );
			break;
		case EVENT_SEEKING_FORWARD:
			g_message( "[Pause] to [seeking]" );	
			mh_dev_forward( _pb->mhDev, _pb );
			break;
		case EVENT_SEEKING_BACKWARD:
			g_message( "[Pause] to [seeking]" );	
			mh_dev_backward( _pb->mhDev, _pb );
			break;
		case EVENT_SEEKING_FORWARD_DONE:
			mh_dev_forward_done( _pb->mhDev, _pb );
			break;
		case EVENT_SEEKING_BACKWARD_DONE:
			mh_dev_backward_done( _pb->mhDev, _pb );
			break;
		default:
			break;
	}
}      /* -----  end of static function action  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _open
 *  Description:
 * =====================================================================================
 */
static void _open( MHState * self, MHPb * pb )
{
	g_message( "Opening [Pause]" );
	mh_pb_state_open( pb, MH_PB_STATE_PAUSE, NULL );
}      /* -----  end of static function open  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _close
 *  Description:
 * =====================================================================================
 */
static void _close( MHState * self, MHPb * pb )
{
	g_message( "Closing [Pause]" );
}      /* -----  end of static function close  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_pause_constructor
 *  Description:  
 * =====================================================================================
 */
static GObject * mh_state_pause_constructor( GType type, guint n_construct_params, 
									GObjectConstructParam * construct_params )
{
	if( pauseObject == NULL )
	{
		pauseObject	=	G_OBJECT_CLASS( mh_state_pause_parent_class )->constructor( type, 
						n_construct_params,	construct_params );
	}

	return pauseObject;
}		/* -----  end of static function mh_state_pause_constructor  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_pause_dispose
 *  Description:
 * =====================================================================================
 */
static void mh_state_pause_dispose( GObject * object )
{
	MHStatePause * _self	=	MH_STATE_PAUSE( object );

	pauseObject	=	NULL;

	G_OBJECT_CLASS( mh_state_pause_parent_class )->dispose( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_pause_finalize
 *  Description:
 * =====================================================================================
 */
static void mh_state_pause_finalize( GObject * object )
{
	MHStatePause * _self	=	MH_STATE_PAUSE( object );
	MHStatePausePrivate * _priv	=	mh_state_pause_get_instance_private( _self );

	G_OBJECT_CLASS( mh_state_pause_parent_class )->finalize( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_pause_init
 *  Description:
 * =====================================================================================
 */
static void mh_state_pause_init( MHStatePause * self )
{
	MHStatePausePrivate * _priv	=	mh_state_pause_get_instance_private( self );
}       /* -----  end of static function mh_state_pause_init  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_pause_class_init
 *  Description:
 * =====================================================================================
 */
static void mh_state_pause_class_init( MHStatePauseClass * klass )
{
	MHStateClass * _parentClass	=	MH_STATE_CLASS( klass );
	GObjectClass * _gobjectClass	=	G_OBJECT_CLASS( klass );

	_gobjectClass->constructor	=	mh_state_pause_constructor;
	_gobjectClass->dispose	=	mh_state_pause_dispose;
	_gobjectClass->finalize	=	mh_state_pause_finalize;

	/* assemble ios of mh_state_pause class */

	/* assemble methods of mh_state_pause class */
	_parentClass->action	=	_action;
	_parentClass->open	=	_open;
	_parentClass->close	=	_close;

	/* Ios */
	/* Signals */
}       /* -----  end of static function mh_state_pause_class_init  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_pause_instance
 *  Description:  
 * =====================================================================================
 */
MHStatePause * mh_state_pause_instance ()
{
	return g_object_new( MH_TYPE_STATE_PAUSE, NULL );
}		/* -----  end of function mh_state_pause_instance  ----- */
