/*
 * Generated by object-codegen.
 */
#include <glib.h>
#include "seeking.h"
#include "stmdefs.h"
#include "switching.h"
#include <mh_dev.h>
#include <mh_pb.h>
#include <mh_playlist.h>

typedef struct _MHStateSeekingPrivate MHStateSeekingPrivate;

struct _MHStateSeekingPrivate
{
	gint dummy;
};

G_DEFINE_TYPE_WITH_PRIVATE( MHStateSeeking, mh_state_seeking, MH_TYPE_STATE )

static GObject * seekingObject;

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _action
 *  Description:
 * =====================================================================================
 */
static void _action( MHState * self, MHPb * pb, guint event, gpointer param1, gpointer param2 )
{
	MHPb * _pb = MH_PB( pb );
	switch( event )
	{
		case EVENT_SEEKING_FORWARD_DONE:
			mh_dev_forward_done( _pb->mhDev, _pb );
			break;
		case EVENT_SEEKING_BACKWARD_DONE:
			mh_dev_backward_done( _pb->mhDev, _pb );
			break;
		case EVENT_SEEKING_FORWARD:
			mh_dev_forward( _pb->mhDev, _pb );
			break;
		case EVENT_SEEKING_BACKWARD:
			mh_dev_backward( _pb->mhDev, _pb );
			break;
		case EVENT_SWITCHING_NEXT:
			g_message( "[seeking] to [switching]" );
			mh_pb_dispatch( _pb, EVENT_CHANGE, GUINT_TO_POINTER( SWITCHING_STATUS ), NULL );
			mh_dev_next( _pb->mhDev, _pb );
			break;

		case EVENT_PLAY:
			if(( _pb->mhDev	!=	NULL ) && ( g_strcmp0( _pb->mhDev->type , "iap2")==0 ))
			{
				g_message( "[seeking] to [Playing]" );
				mh_dev_play( _pb->mhDev, _pb );
			}
			else
			{
				g_message( "not support [seeking] to [Playing]" );
			}
			break;
		case EVENT_PAUSE:
			if(( _pb->mhDev	!=	NULL ) && ( g_strcmp0( _pb->mhDev->type , "iap2")==0 ))
			{
				g_message( "[switching] to [Pause]" );
				mh_dev_pause( _pb->mhDev, _pb );
			}
			else
			{
				g_message( "not support [seeking] to [Pause]" );
			}
			break;
		case EVENT_SWITCHING_PREVIOUS:
			if(( _pb->mhDev	!=	NULL ) && ( g_strcmp0( _pb->mhDev->type , "iap2")==0 ))
			{
				g_message( "[seeking] to [switching]" );
				mh_pb_dispatch( _pb, EVENT_CHANGE, GUINT_TO_POINTER( SWITCHING_STATUS ), NULL );
				mh_dev_previous( _pb->mhDev, _pb );
			}
			else
			{
				g_message( "not support [seeking] to [switching]" );
			}
			break;
		case EVENT_SWITCHING_SELECT:
			if( _pb->playlist != NULL && ( _pb->mhDev	!=	NULL ) && ( g_strcmp0( _pb->mhDev->type , "iap2")==0 ))
			{
				mh_dev_set_index( _pb->mhDev, _pb, ( uint32_t )_pb->playlist->index );
			}else{
				g_message("seek %s playlist is NULL!!",__func__);		
			}
			break;
		case EVENT_SEEKING:
			if(( _pb->mhDev	!=	NULL ) && ( g_strcmp0( _pb->mhDev->type , "iap2")==0 ))
			{
				mh_pb_dispatch( _pb, EVENT_CHANGE, GUINT_TO_POINTER( SEEKING_STATUS ), GUINT_TO_POINTER( PAUSE_STATUS ) );
				mh_dev_seek( _pb->mhDev, _pb, ( uint32_t )_pb->seeking_pos );
			}
			else
			{
				g_message( "not support [seeking] to [seeking]" );
			}
			break;

		default:
			break;
	}
}      /* -----  end of static function action  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _open
 *  Description:
 * =====================================================================================
 */
static void _open( MHState * self, MHPb * pb )
{
	g_message( "Opening [seeking]" );
	mh_pb_state_open( pb, MH_PB_STATE_SEEKING, NULL );
}      /* -----  end of static function open  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _close
 *  Description:
 * =====================================================================================
 */
static void _close( MHState * self, MHPb * pb )
{
	g_message( "Closing [seeking]" );
}      /* -----  end of static function close  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_seeking_dispose
 *  Description:
 * =====================================================================================
 */
static void mh_state_seeking_dispose( GObject * object )
{
	MHStateSeeking * _self	=	MH_STATE_SEEKING( object );

	seekingObject	=	NULL;

	G_OBJECT_CLASS( mh_state_seeking_parent_class )->dispose( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_seeking_finalize
 *  Description:
 * =====================================================================================
 */
static void mh_state_seeking_finalize( GObject * object )
{
	MHStateSeeking * _self	=	MH_STATE_SEEKING( object );
	MHStateSeekingPrivate * _priv	=	mh_state_seeking_get_instance_private( _self );

	G_OBJECT_CLASS( mh_state_seeking_parent_class )->finalize( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_seeking_init
 *  Description:
 * =====================================================================================
 */
static void mh_state_seeking_init( MHStateSeeking * self )
{
	MHStateSeekingPrivate * _priv	=	mh_state_seeking_get_instance_private( self );
}       /* -----  end of static function mh_state_seeking_init  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_seeking_constructor
 *  Description:  
 * =====================================================================================
 */
static GObject * mh_state_seeking_constructor( GType type, guint n_construct_params, 
									GObjectConstructParam * construct_params )
{
	if( seekingObject == NULL )
	{
		seekingObject	=	G_OBJECT_CLASS( mh_state_seeking_parent_class )->constructor( type, 
						n_construct_params,	construct_params );
	}

	return seekingObject;
}		/* -----  end of static function mh_state_seeking_constructor  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_seeking_class_init
 *  Description:
 * =====================================================================================
 */
static void mh_state_seeking_class_init( MHStateSeekingClass * klass )
{
	MHStateClass * _parentClass	=	MH_STATE_CLASS( klass );
	GObjectClass * _gobjectClass	=	G_OBJECT_CLASS( klass );

	_gobjectClass->constructor	=	mh_state_seeking_constructor;
	_gobjectClass->dispose	=	mh_state_seeking_dispose;
	_gobjectClass->finalize	=	mh_state_seeking_finalize;

	/* assemble ios of mh_state_seeking class */

	/* assemble methods of mh_state_seeking class */
	_parentClass->action	=	_action;
	_parentClass->open	=	_open;
	_parentClass->close	=	_close;

	/* Ios */
	/* Signals */
}       /* -----  end of static function mh_state_seeking_class_init  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_state_seeking_instance
 *  Description:  
 * =====================================================================================
 */
MHStateSeeking * mh_state_seeking_instance()
{
	return g_object_new( MH_TYPE_STATE_SEEKING, NULL );
}		/* -----  end of function mh_state_seeking_instance  ----- */
