/*
 * Generated by object-codegen.
 */
#include <glib.h>
#include <mh_dev.h>
#include <mh_playlist.h>
#include <mh_col.h>
#include <mh_contents.h>
#include <stdio.h>
#include <string.h>
#include <mh_pb.h>

typedef struct _MHDevPrivate MHDevPrivate;

struct _MHDevPrivate
{
	gint dummy;
};

G_DEFINE_TYPE_WITH_PRIVATE( MHDev, mh_dev, MH_TYPE_IO )

enum
{
	PROP_0,

	PROP_DEV_TYPE,
	PROP_DEV_ENTRY,
	PROP_DEV_SERIAL,
	PROP_DEV_PID,
	PROP_DEV_VID,
	PROP_DEV_SEARCHTYPE,
	PROP_DEV_IAPTYPE,
	PROP_DEV_PATH,

	N_PROPERTIES
};

enum {
	/* Ios */

	/* Signals */
//	START,
//	UPDATE,
//	FINISH,
	DEV_EVENTS,
	DEV_DETACH,
	DEV_STATUS,

	N_SIGNALS
};

static GParamSpec * devProperties[ N_PROPERTIES ]	=	{ NULL, };
#define MEDIA_CATEGORY 3
static guint signals[ N_SIGNALS ] = {0};

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _play_by_list
 *  Description:
 * =====================================================================================
 */
static void _play_by_list( MHDev * self, MHPb * pb, MHPlaylist * playlist )
{

	//Method default implement.
	
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
				__func__);
}      /* -----  end of static function _play_by_list  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _play_radio_by_index
 *  Description:
 * =====================================================================================
 */
static void _play_radio_by_index( MHDev * self, MHPb * pb, uint32_t index ) 
{

	//Method default implement.
	
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
				__func__);
}      /* -----  end of static function _play_by_list  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _stop
 *  Description:
 * =====================================================================================
 */
static void _stop( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
				__func__);
}      /* -----  end of static function _stop  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _close
 *  Description:
 * =====================================================================================
 */
static void _close( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
				__func__);
}      /* -----  end of static function _close  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _play
 *  Description:
 * =====================================================================================
 */
static void _play( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
				__func__);
}      /* -----  end of static function _play  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _pause
 *  Description:
 * =====================================================================================
 */
static void _pause( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
				__func__);
}      /* -----  end of static function _pause  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _seek
 *  Description:
 * =====================================================================================
 */
static void _seek( MHDev * self, MHPb * pb, uint32_t second )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _seek  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _next
 *  Description:
 * =====================================================================================
 */
static void _next( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _next  ----- */  

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _previous
 *  Description:
 * =====================================================================================
 */
static void _previous( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _next  ----- */  

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _play_pause
 *  Description:
 * =====================================================================================
 */
static void _play_pause( MHDev * self )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _play_pause  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _resume
 *  Description:
 * =====================================================================================
 */
static void _resume( MHDev * self )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _resume  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _forward
 *  Description:
 * =====================================================================================
 */
static void _forward( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _forward  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _forward_done
 *  Description:
 * =====================================================================================
 */
static void _forward_done( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _forward_done  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _backward
 *  Description:
 * =====================================================================================
 */
static void _backward( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _backward  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _backward_done
 *  Description:
 * =====================================================================================
 */
static void _backward_done( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _backward_done  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_index
 *  Description:
 * =====================================================================================
 */
static void _set_index( MHDev * self, MHPb * pb, uint32_t index )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_index  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _resize
 *  Description:
 * =====================================================================================
 */
static void _resize( MHDev * self, MHPb * pb, uint32_t offsetx, uint32_t offsety, uint32_t width, uint32_t height )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _resize  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _pixel_aspect_ratio
 *  Description:
 * =====================================================================================
 */
static void _pixel_aspect_ratio( MHDev * self, MHPb * pb, uint32_t pixel_n, uint32_t pixel_d )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _pixel_aspect_ratio  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_pipeline_status
 *  Description:
 * =====================================================================================
 */
static void _set_pipeline_status( MHDev * self, MHPb * pb, uint32_t status )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_pipeline_status  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _audiobook_playback_speed
 *  Description:
 * =====================================================================================
 */
static void _audiobook_playback_speed( MHDev * self, MHPb * pb, uint32_t status )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _audiobook_playback_speed  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_video_sink
 *  Description:
 * =====================================================================================
 */
static void _set_video_sink( MHDev * self, MHPb * pb, const char * video_sink_name )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_video_sink  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_speed
 *  Description:
 * =====================================================================================
 */
static void _set_speed( MHDev * self, guint speed )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_speed  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_repeat
 *  Description:
 * =====================================================================================
 */
static void _set_repeat( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_repeat  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_media_info
 *  Description:
 * =====================================================================================
 */
static void _set_media_info( MHDev * self, MHPb * pb, guint type, void * user_data )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_media_info  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_shuffle
 *  Description:
 * =====================================================================================
 */
static void _set_shuffle( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_shuffle  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_rate
 *  Description:
 * =====================================================================================
 */
static void _set_rate( MHDev * self, MHPb * pb )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_rate  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_buffer_time
 *  Description:
 * =====================================================================================
 */
static void _set_buffer_time( MHDev * self )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _set_buffer_time  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _playlist_change
 *  Description:
 * =====================================================================================
 */
static void _playlist_change( MHDev * self, MHPb * pb, MHPlaylist * playlist )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _playlist_change  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _create_playlist
 *  Description:  
 * =====================================================================================
 */
static MHPlaylist * _create_playlist( MHDev * self )
{
	MHPlaylist * _playlist	=	g_object_new( MH_TYPE_PLAYLIST, NULL );

	_playlist->dev	=	self;

	return _playlist;
}		/* -----  end of static function _create_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _restore_playlist
 *  Description:  
 * =====================================================================================
 */
static MHPlaylist * _restore_playlist( MHDev * self,gint64 playlist_id )
{
	g_message("\n\n\n%s\n\n\n", __func__);
	MHPlaylist * _playlist	=	NULL;
	void * _buf;
	int _size;
	GVariant * _data	=	NULL;
	GVariant * _list	=	NULL;

	_buf	=	mh_contents_restore_playlist( mh_contents_instance(),playlist_id ,&_size);

	if( _buf != NULL )
		_data	=	g_variant_new_from_data( G_VARIANT_TYPE( "(vuuuuu)" ), _buf, _size, TRUE, NULL, NULL );

	if( _data != NULL )
	{
		GVariantIter * _iter;
		gchar * _uri	=	NULL, * _name	=	NULL;
		MHItemType _type;
		GVariant * _metadata	=	NULL;
		guint _seq, _num;
		gint64 _id;
		int _offset	=	0;

		_playlist	=	g_object_new( MH_TYPE_PLAYLIST, NULL );
		_playlist->dev	=	 self;

		g_variant_get( _data, "(vuuuuu)", &_list, &_playlist->index, &_playlist->ptime,
				&_playlist->shuffle, &_playlist->repeat, &_playlist->error_count );
//		g_message("index:%d,ptime:%d", _playlist->index, _playlist->ptime);
		_iter   =   g_variant_iter_new( _list );

		_num	=	g_variant_iter_n_children( _iter );

		_playlist->seq	=	g_new0( uint32_t, _num );

		while( g_variant_iter_loop( _iter, "(susxuv)", &_uri, &_type, &_name, &_id, &_seq, &_metadata ))
		{
			MHItemData * _itemData	=	g_slice_new0( MHItemData );
			_itemData->uri	=	g_strdup( _uri );
			_itemData->type	=	_type;
			_itemData->name	=	g_strdup( _name );
			_itemData->uniqueId	=	_id;
			_itemData->valid	=	MH_ITEM_UNKNOWN;
			/* TODO: Metadata */
			if( _type	==	 MH_ITEM_MUSIC)
			{
				g_variant_get(_metadata, "(sssssiiiii)", &(_itemData->metadata.music.title), &(_itemData->metadata.music.album),
						&(_itemData->metadata.music.artist), &(_itemData->metadata.music.genre), &(_itemData->metadata.music.composer),
						&(_itemData->metadata.music.year), &(_itemData->metadata.music.track), &(_itemData->metadata.music.trackCount),
						&(_itemData->metadata.music.mediaType), &(_itemData->metadata.music.duration));
//				g_message("%s--->title:%s, artist:%s", __func__, _itemData->metadata.music.title, _itemData->metadata.music.artist);
			}
//			g_message("%d:%s->%s", _offset, _itemData->name, _itemData->uri);

			g_array_append_vals( _playlist->array, &_itemData, 1 );
			_playlist->seq[ _offset ++ ]	=	_seq;
		}

		g_variant_iter_free( _iter );

		g_variant_unref( _list );

		g_variant_unref( _data );
	}
	
	return _playlist;
}		/* -----  end of static function _restore_playlist  ----- */


/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _register_detach_listener
 *  Description:  
 * =====================================================================================
 */
static uint32_t  _register_detach_listener(MHDev * self,MHDevDetachListener * listener )
{
	g_signal_connect(self,"dev_detach",G_CALLBACK(listener->callback),listener->user_data);	

	return 0;
}		/* -----  end of static function _register_detach_listener  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _get_playlist_info
 *  Description:  
 * =====================================================================================
 */
static MHPlaylistInfo *  _get_playlist_info( MHDev * self)
{
	char * _sql	=	"select playlist_id,name from playlist left join devices "
		"on playlist.device_id=devices.device_id where devices.serial_number = '%s'";
	char _buf[1024];
	MHContents * _contents;
	MHStmt * _statement;
	gint64 _playlistId;
	gchar * _name;
	int _count	=	0, _alloc	=	1;
	MHPlaylistInfo * _res	=	g_malloc0( _alloc * sizeof( MHPlaylistInfo ));

	sprintf( _buf, _sql, self->serial );

	_contents	=	mh_contents_instance();
	_statement	=	mh_contents_prepare( _contents, _buf);

	while( mh_contents_step( _contents, _statement, &_playlistId, &_name, 
				NULL) == MH_CONTENTS_STEP_CONTINUE)
	{
		_count	++;

		while( _alloc <= _count )
		{
			_alloc	=	_alloc << 1;

			_res	=	g_realloc( _res, _alloc * sizeof( MHPlaylistInfo ));

			memset( _res + _count, 0, ( _alloc - _count ) * sizeof( MHPlaylistInfo ) );
		}

		_res[ _count - 1 ].name	=	_name;
		_res[ _count - 1 ].playlistid	=	_playlistId;
	}

	mh_contents_release( _contents, _statement);

	return _res;
}		/* -----  end of static function _get_playlist_info  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _save_playlist
 *  Description:  
 * =====================================================================================
 */
static void  _save_playlist( MHDev * self, const char * name, MHPlaylist * playlist)
{
	gint64 _res;
	
	GVariantBuilder * _builder;
	GVariant * _list, * _data;
	int i;

	_builder	=	g_variant_builder_new( G_VARIANT_TYPE( "a(susxuv)" ));

	for( i = 0; i < playlist->array->len; i ++ )
	{
		MHItemData * _item	=	g_array_index( playlist->array, MHItemData *, i );
		GVariant * _metadata;
		if( _item->type == MH_ITEM_MUSIC)
		{
			_metadata	=	g_variant_new("(sssssiiiii)",
					_item->metadata.music.title ? _item->metadata.music.title : "",
					_item->metadata.music.album ? _item->metadata.music.album : "",
					_item->metadata.music.artist ? _item->metadata.music.artist : "",
					_item->metadata.music.genre ? _item->metadata.music.genre : "",
					_item->metadata.music.composer ? _item->metadata.music.composer : "",
					_item->metadata.music.year, _item->metadata.music.track, _item->metadata.music.trackCount,
					_item->metadata.music.mediaType, _item->metadata.music.duration);
		}
		else
		{
			_metadata	=	g_variant_new_string("");
		}
		g_variant_builder_add( _builder, "(susxuv)", _item->uri, _item->type, _item->name, _item->uniqueId,playlist->seq[i], _metadata );
	}

	_list	=	g_variant_builder_end( _builder );

	g_variant_builder_unref( _builder );

	_data	=	g_variant_new( "(vuuuuu)", _list, playlist->index, playlist->ptime, 
			playlist->shuffle, playlist->repeat, playlist->error_count );

	MHContents * _contents	=	mh_contents_instance();
	
	_res	=	mh_contents_save_playlist( _contents, self, name,playlist->tag_id, (gpointer)g_variant_get_data( _data ), g_variant_get_size( _data ));

	g_variant_unref( _data );

//	return _res;
}		/* -----  end of static function _save_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _update_playlist
 *  Description:  
 * =====================================================================================
 */
static void _update_playlist( MHDev * self, const char * name, MHPlaylist * playlist, gint64 playlist_id)
{

	MHContents * _contents	=	mh_contents_instance();

	GVariantBuilder * _builder;
	GVariant * _list, * _data;
	int i;

	_builder	=	g_variant_builder_new( G_VARIANT_TYPE( "a(susxuv)" ));

	for( i = 0; i < playlist->array->len; i ++ )
	{
		MHItemData * _item	=	g_array_index( playlist->array, MHItemData *, i );
		GVariant * _metadata;
		if( _item->type == MH_ITEM_MUSIC)
		{
			_metadata	=	g_variant_new("(sssssiiiii)",
					_item->metadata.music.title ? _item->metadata.music.title : "",
					_item->metadata.music.album ? _item->metadata.music.album : "",
					_item->metadata.music.artist ? _item->metadata.music.artist : "",
					_item->metadata.music.genre ? _item->metadata.music.genre : "",
					_item->metadata.music.composer ? _item->metadata.music.composer : "",
					_item->metadata.music.year, _item->metadata.music.track, _item->metadata.music.trackCount,
					_item->metadata.music.mediaType, _item->metadata.music.duration);
		}
		else
		{
			_metadata	=	g_variant_new_string("");
		}
		g_variant_builder_add( _builder, "(susxuv)", _item->uri, _item->type, _item->name, _item->uniqueId,playlist->seq[i], _metadata );
	}

	_list	=	g_variant_builder_end( _builder );

	g_variant_builder_unref( _builder );

	_data	=	g_variant_new( "(vuuuuu)", _list, playlist->index, playlist->ptime, 
			playlist->shuffle, playlist->repeat, playlist->error_count);

	mh_contents_update_playlist( _contents, self, playlist_id,name, playlist->tag_id, (gpointer)g_variant_get_data( _data ), g_variant_get_size( _data ));

	g_variant_unref( _data );
}		/* -----  end of static function _update_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _delete_playlist
 *  Description:  
 * =====================================================================================
 */
static void _delete_playlist( MHDev * self, gint64 playlist_id)
{
	MHContents * _contents	=	mh_contents_instance();
	
	mh_contents_delete_playlist( _contents, playlist_id);
}		/* -----  end of static function _delete_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _get_radiolist
 *  Description:  
 * =====================================================================================
 */
static char ** _get_radiolist( MHDev * self, int * count)
{
	char ** res;
	
	g_message("%s", __func__);
	
	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
	return res;
}		/* -----  end of static function _get_radiolist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _get_property
 *  Description:  
 * =====================================================================================
 */
static void _get_property( GObject * object, guint property_id, GValue * value,
		GParamSpec * spec)
{
	MHDev * _self	=	MH_DEV( object );
	
	if (NULL == _self)
	{
		g_message("%s dev _self == NULL", __func__);
		return;
	}

	switch( property_id )
	{
	case PROP_DEV_TYPE:
		g_value_set_string( value, _self->type );
		break;
	case PROP_DEV_ENTRY:
		g_value_set_string( value, _self->entry );
		break;
	case PROP_DEV_SERIAL:
		g_value_set_string( value, _self->serial );
		break;
	case PROP_DEV_PID:
		g_value_set_string( value, _self->pid );
		break;
	case PROP_DEV_VID:
		g_value_set_string( value, _self->vid );
		break;
	case PROP_DEV_SEARCHTYPE:
		g_value_set_uint( value, _self->searchType );
		g_message("%s _self->searchType = %d",__func__,_self->searchType);
		break;
	case PROP_DEV_IAPTYPE:
		g_value_set_uint( value, _self->iapType );
		g_message("%s _self->iapType = %d",__func__,_self->iapType);
		break;
	case PROP_DEV_PATH:
		if (_self->devPath != NULL)
		{
			g_value_set_string( value, _self->devPath );
			g_message("%s _self->devPath = %s",__func__,_self->devPath);
		}
		else
		{
			g_message("%s _self->devPath = NULL",__func__);
		}
		break;

	default:
		break;
	}
}		/* -----  end of static function _get_property  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _set_property
 *  Description:  
 * =====================================================================================
 */
static void _set_property( GObject * object, guint property_id, const GValue * value,
		GParamSpec * spec)
{
	MHDev * _self	=	MH_DEV( object );
	
	if (NULL == _self)
	{
		g_message("%s dev _self == NULL", __func__);
		return;
	}

	switch( property_id )
	{
	case PROP_DEV_SEARCHTYPE:
		_self->searchType = g_value_get_uint( value );
		g_message("%s _self->searchType = %d",__func__,_self->searchType);
		break;

	default:
		break;
	}
}		/* -----  end of static function _set_property  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _register_scan_callback
 *  Description:  
 * =====================================================================================
 */
static uint32_t  _register_events_listener(MHDev * self, MHDevEventsListener * listener)
{
	g_signal_connect( self,"dev_events",G_CALLBACK(listener->callback),listener->user_data);
	return 0;
}		/* -----  end of static function _register_scan_callback  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _attach_pb
 *  Description:  
 * =====================================================================================
 */
static void _attach_pb( MHDev * self, MHPb * pb )
{

	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);

}		/* -----  end of static function _attach_pb  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _dispose
 *  Description:
 * =====================================================================================
 */
static void _dispose( GObject * object )
{
	MHDev * _self	=	MH_DEV( object );

	G_OBJECT_CLASS( mh_dev_parent_class )->dispose( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _finalize
 *  Description:
 * =====================================================================================
 */
static void _finalize( GObject * object )
{
	MHDev * _self	=	MH_DEV( object );
	MHDevPrivate * _priv	=	mh_dev_get_instance_private( _self );

	G_OBJECT_CLASS( mh_dev_parent_class )->finalize( object );
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_init
 *  Description:
 * =====================================================================================
 */
static void mh_dev_init( MHDev * self )
{
	MHDevPrivate * _priv	=	mh_dev_get_instance_private( self );
	self->uniqueId	=	0;
	self->type	=	NULL;
	self->entry	=	NULL;
	self->serial	=	NULL;
	self->pid	=	NULL;
	self->vid	=	NULL;
	self->itemsHash	=	g_hash_table_new( g_int64_hash, g_int64_equal);
	self->dev_status	=	true;
	self->scanType		=	SCAN_FOLDER;	
	self->searchType	=	DEPTH_FIRST;
	self->iapType		=	MISC_IAP;
	self->devPath		=	NULL;
}       /* -----  end of static function mh_dev_init  ----- */

typedef struct _signal_param 
{
	MHDev * dev;
	char * name;
	va_list list;
} signal_param;				/* ----------  end of struct signal_param  ---------- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _emit_signal
 *  Description:  
 * =====================================================================================
 */
static gboolean _emit_signal( gpointer user_data)
{
	signal_param * _param	=	(signal_param *)user_data;

	GType _itype; 

	guint _signal_id;	
	if( MH_IS_DEV( _param->dev))
	{
		_itype	=	MH_TYPE_DEV;

		_signal_id	=	g_signal_lookup( _param->name, _itype);

		g_signal_emit_valist( _param->dev, _signal_id, 0, _param->list);

		va_end( _param->list);
	}
	return FALSE;

}		/* -----  end of static function _emit_signal  ----- */
/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _scan_abort
 *  Description:  
 * =====================================================================================
 */
static void _scan_abort( MHDev * dev)
{
	dev->dev_status	=	false;
}		/* -----  end of static function _scan_abort  ----- */
/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _signal_emit_by_name
 *  Description:  
 * =====================================================================================
 */
static void _signal_emit_by_name( MHDev * self, const char * name,va_list param)
{
	GSource * _source	=	g_idle_source_new();

	signal_param * _param	=	g_new( signal_param, 1);

	_param->dev		=	self;
	_param->name	=	g_strdup(name);
	va_copy(_param->list, param);
//	_param->list	=	param;

	g_source_set_callback( _source, _emit_signal, ( gpointer )_param, NULL);

	mh_io_dispatch( MH_IO(self), _source );

	g_source_unref( _source);


	
}		/* -----  end of static function _signal_emit_by_name  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _create_empty_playlist
 *  Description:  
 * =====================================================================================
 */
static MHPlaylist * _create_empty_playlist( MHDev * self)
{
	MHPlaylist * _playlist	=	g_object_new( MH_TYPE_PLAYLIST, NULL );

	_playlist->dev	=	self;
	return _playlist;
}		/* -----  end of static function _create_empty_playlist  ----- */
/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _start
 *  Description:
 * =====================================================================================
 */
static void _start( MHDev * self )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _start  ----- */
/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _send_signal_touch
 *  Description:
 * =====================================================================================
 */
static void _send_signal_touch( MHDev * self,MHTouchType press, guint x , guint y )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
}      /* -----  end of static function _send_signal_touch  ----- */


/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _register_status_listener
 *  Description:  
 * =====================================================================================
 */
static void _register_status_listener(MHDev * self, MHDevStatusListener * listener )
{
	g_signal_connect( self, "dev_status", G_CALLBACK( listener->callback), listener->user_data);

}		/* -----  end of static function _register_status_listener  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _add_file
 *  Description:  
 * =====================================================================================
 */
static MHItem * _add_file( MHDev * dev, MHFolder * folder, MHItem * item)
{	
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
	return NULL;
}		/* -----  end of static function _add_file  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  _delete_file
 *  Description:  
 * =====================================================================================
 */
static MHResult _delete_file( MHDev * dev , MHItem * item)
{
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
	return MH_FUNC_NOT_IMPLEMENT;
}		/* -----  end of static function _delete_file  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  _register_module_status
 *  Description:
 * =====================================================================================
 */
static MHResult _register_module_status( MHDev * self, ModuleStatusListener * listener )
{

	//Method default implement.
	g_critical( "implement the pure virtual function 'MHDevClass::%s' is Failed!",
			__func__);
	return MH_FUNC_NOT_IMPLEMENT;
}      /* -----  end of static function _register_module_status  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_class_init
 *  Description:
 * =====================================================================================
 */
static void mh_dev_class_init( MHDevClass * klass )
{
	MHIoClass * _parentClass	=	MH_IO_CLASS( klass );
	GObjectClass * _gobjectClass	=	G_OBJECT_CLASS( klass );

	_gobjectClass->dispose	=	_dispose;
	_gobjectClass->finalize	=	_finalize;
	_gobjectClass->get_property	=	_get_property;
	_gobjectClass->set_property	=	_set_property;

	/* assemble ios of mh_dev class */

	/* assemble methods of mh_dev class */
	klass->play_by_list	=	_play_by_list;
	klass->play_radio_by_index	=	_play_radio_by_index;
	klass->stop	=	_stop;
	klass->close	=	_close;
	klass->play	=	_play;
	klass->pause	=	_pause;
	klass->play_pause	=	_play_pause;
	klass->resume	=	_resume;
	klass->forward	=	_forward;
	klass->forward_done	=	_forward_done;
	klass->backward	=	_backward;
	klass->backward_done	=	_backward_done;
	klass->set_index	=	_set_index;
	klass->set_speed	=	_set_speed;
	klass->set_repeat	=	_set_repeat;
	klass->set_shuffle	=	_set_shuffle;
	klass->set_rate	=	_set_rate;
	klass->set_buffer_time	=	_set_buffer_time;
	klass->next	=	_next;
	klass->previous	=	_previous;
	klass->create_playlist	=	_create_playlist;
	klass->seek		=	_seek;
	klass->restore_playlist	=	_restore_playlist;
	klass->playlist_change	=	_playlist_change;
	klass->register_detach_listener	=	_register_detach_listener;
	klass->resize	=	_resize;
	klass->pixel_aspect_ratio	=	_pixel_aspect_ratio;
	klass->set_video_sink	=	_set_video_sink;
	klass->set_media_info	=	_set_media_info;
	klass->get_playlist_info	=	_get_playlist_info;

	klass->save_playlist	=	_save_playlist;
	klass->update_playlist	=	_update_playlist;
	klass->delete_playlist	=	_delete_playlist;
	klass->get_radiolist	=	_get_radiolist;

	klass->register_events_listener	=	_register_events_listener;
	klass->attach_pb	=	_attach_pb;
	klass->signal_emit_by_name	=	_signal_emit_by_name;
	klass->scan_abort	=	_scan_abort;	
	klass->create_empty_playlist	=	_create_empty_playlist;
	klass->set_pipeline_status	=	_set_pipeline_status;
	klass->audiobook_playback_speed	=	_audiobook_playback_speed;
	klass->send_signal_touch	=	_send_signal_touch;
	klass->start	=	_start;
	klass->register_status_listener	=	_register_status_listener;
	klass->add_file	=	_add_file;
	klass->delete_file	=	_delete_file;
	klass->register_module_status	=	_register_module_status;
	/* Ios */
	/* Signals */
//	signals[ START ]	=
//		g_signal_new( "start",
//				G_TYPE_FROM_CLASS( klass ),
//				G_SIGNAL_RUN_LAST,
//				0,
//				NULL,
//				NULL,
//				g_cclosure_marshal_generic,
//				G_TYPE_NONE,
//				0
//				 );
//
//	signals[ UPDATE ]	=
//		g_signal_new( "update",
//				G_TYPE_FROM_CLASS( klass ),
//				G_SIGNAL_RUN_LAST,
//				0,
//				NULL,
//				NULL,
//				g_cclosure_marshal_generic,
//				G_TYPE_NONE,
//				0
//				 );
//
//	signals[ FINISH ]	=
//		g_signal_new( "finish",
//				G_TYPE_FROM_CLASS( klass ),
//				G_SIGNAL_RUN_LAST,
//				0,
//				NULL,
//				NULL,
//				g_cclosure_marshal_generic,
//				G_TYPE_NONE,
//				0
//				 );
	signals[DEV_EVENTS]	=	
		g_signal_new("dev_events",
				G_TYPE_FROM_CLASS(klass),
				G_SIGNAL_RUN_LAST,
				0,
				NULL,
				NULL,
				g_cclosure_marshal_generic,
				G_TYPE_NONE,
				4,
				G_TYPE_UINT,G_TYPE_UINT,G_TYPE_POINTER,G_TYPE_UINT);

	signals[DEV_DETACH]	=	
		g_signal_new("dev_detach",
				G_TYPE_FROM_CLASS( klass ),
				G_SIGNAL_RUN_LAST,
				0,
				NULL,
				NULL,
				g_cclosure_marshal_generic,
				G_TYPE_NONE,
				0);
	signals[DEV_STATUS]	=	
		g_signal_new("dev_status",
				G_TYPE_FROM_CLASS( klass ),
				G_SIGNAL_RUN_LAST,
				0,
				NULL,
				NULL,
				g_cclosure_marshal_generic,
				G_TYPE_NONE,
				1, G_TYPE_UINT);
	
	devProperties[ PROP_DEV_TYPE ]	=	
		g_param_spec_string( "type", "MHDev property", "Type of device",
				"", G_PARAM_READABLE );	

	devProperties[ PROP_DEV_ENTRY ]	=	
		g_param_spec_string( "entry", "MHDev property", "Mount point of device",
				"", G_PARAM_READABLE );

	devProperties[ PROP_DEV_SERIAL ]	=	
		g_param_spec_string( "serial", "MHDev property", "serial of device",
				"", G_PARAM_READABLE );
	
	devProperties[ PROP_DEV_PID ]	=	
	g_param_spec_string( "pid", "MHDev property", "pid of device",
			"", G_PARAM_READABLE );
	
	devProperties[ PROP_DEV_VID ]	=	
	g_param_spec_string( "vid", "MHDev property", "vid of device",
			"", G_PARAM_READABLE );

	devProperties[ PROP_DEV_SEARCHTYPE ]	=	
		g_param_spec_uint( "searchType", "MHDev property", "searchType of device",
				0, G_MAXUINT, 0, G_PARAM_WRITABLE  );

	devProperties[ PROP_DEV_IAPTYPE ]	=	
		g_param_spec_uint( "iapType", "MHDev property", "dev iap type",
				0, G_MAXUINT, 0, G_PARAM_READWRITE );

	devProperties[ PROP_DEV_PATH ]	=	
		g_param_spec_string( "path", "MHDev property", "path of device",
				"", G_PARAM_READABLE );

	g_object_class_install_properties( _gobjectClass, N_PROPERTIES, devProperties );
}       /* -----  end of static function mh_dev_class_init  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_play_radio_by_index
 *  Description:
 * =====================================================================================
 */
void mh_dev_play_radio_by_index( MHDev * self, MHPb * pb, uint32_t index ) 
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->play_radio_by_index != NULL )
	{
		MH_DEV_GET_CLASS( self )->play_radio_by_index( self, pb, index );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::play_by_list()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_play_radio_by_index  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_play_by_list
 *  Description:
 * =====================================================================================
 */
void mh_dev_play_by_list( MHDev * self, MHPb * pb, MHPlaylist * playlist )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->play_by_list != NULL )
	{
		MH_DEV_GET_CLASS( self )->play_by_list( self, pb, playlist );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::play_by_list()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_play_by_list  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_stop
 *  Description:
 * =====================================================================================
 */
void mh_dev_stop( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->stop != NULL )
	{
		MH_DEV_GET_CLASS( self )->stop( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::stop()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_stop  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_close
 *  Description:
 * =====================================================================================
 */
void mh_dev_close( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->close != NULL )
	{
		MH_DEV_GET_CLASS( self )->close( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::stop()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_close  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_play
 *  Description:
 * =====================================================================================
 */
void mh_dev_play( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->play != NULL )
	{
		MH_DEV_GET_CLASS( self )->play( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::play()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_play  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_next
 *  Description:
 * =====================================================================================
 */
void mh_dev_next( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->next != NULL )
	{
		MH_DEV_GET_CLASS( self )->next( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::play()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_previous
 *  Description:
 * =====================================================================================
 */
void mh_dev_previous( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->previous != NULL )
	{
		MH_DEV_GET_CLASS( self )->previous( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::play()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}	

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_pause
 *  Description:
 * =====================================================================================
 */
void mh_dev_pause( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->pause != NULL )
	{
		MH_DEV_GET_CLASS( self )->pause( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::pause()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_pause  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_play_pause
 *  Description:
 * =====================================================================================
 */
void mh_dev_play_pause( MHDev * self )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->play_pause != NULL )
	{
		MH_DEV_GET_CLASS( self )->play_pause( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::play_pause()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_play_pause  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_resume
 *  Description:
 * =====================================================================================
 */
void mh_dev_resume( MHDev * self )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->resume != NULL )
	{
		MH_DEV_GET_CLASS( self )->resume( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::resume()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_resume  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_forward
 *  Description:
 * =====================================================================================
 */
void mh_dev_forward( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->forward != NULL )
	{
		MH_DEV_GET_CLASS( self )->forward( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::forward()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_forward  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_forward_done
 *  Description:
 * =====================================================================================
 */
void mh_dev_forward_done( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->forward_done != NULL )
	{
		MH_DEV_GET_CLASS( self )->forward_done( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::forward_done()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_forward_done  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_backward
 *  Description:
 * =====================================================================================
 */
void mh_dev_backward( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->backward != NULL )
	{
		MH_DEV_GET_CLASS( self )->backward( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::backward()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_backward  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_backward_done
 *  Description:
 * =====================================================================================
 */
void mh_dev_backward_done( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->backward_done != NULL )
	{
		MH_DEV_GET_CLASS( self )->backward_done( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::backward_done()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_backward_done  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_index
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_index( MHDev * self, MHPb * pb, uint32_t index )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_index != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_index( self, pb, index );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_index()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_index  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_speed
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_speed( MHDev * self, guint speed )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_speed != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_speed( self, speed );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_speed()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_speed  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_repeat
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_repeat( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_repeat != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_repeat( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_repeat()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_repeat  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_shuffle
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_shuffle( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_shuffle != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_shuffle( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_shuffle()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_shuffle  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_rate
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_rate( MHDev * self, MHPb * pb )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_rate != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_rate( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_rate()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_rate  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_buffer_time
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_buffer_time( MHDev * self )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_buffer_time != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_buffer_time( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_buffer_time()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_buffer_time  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_start_scan
 *  Description:
 * =====================================================================================
 */
MHResult mh_dev_start_scan( MHDev * self, MHDevScanType type )
{
	printf("[%s : %s : %d][type : %d]\n", __FILE__, __func__, __LINE__, type);
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM);

	MHResult _res	=	MH_OK;
	if( MH_DEV_GET_CLASS( self )->start_scan != NULL )
	{
		MH_DEV_GET_CLASS( self )->start_scan( self, type);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::start_scan()'",
				G_OBJECT_TYPE_NAME( self ));

		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_start_scan  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_get_properties
 *  Description:  
 * =====================================================================================
 */
bool mh_dev_get_properties( MHDev * self, const char * first_property_name, ... )
{
	va_list _varArgs;

	g_return_val_if_fail( MH_IS_DEV( self ), false );

	va_start( _varArgs, first_property_name );

	g_object_get_valist( G_OBJECT( self ), first_property_name, _varArgs );

	va_end( _varArgs );

	return true;
}		/* -----  end of function mh_dev_get_properties  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_properties
 *  Description:  
 * =====================================================================================
 */
bool mh_dev_set_properties( MHDev * self, const char * first_property_name, ... )
{
	va_list _varArgs;

	g_return_val_if_fail( MH_IS_DEV( self ), false );

	va_start( _varArgs, first_property_name );

	g_object_set_valist( G_OBJECT( self ), first_property_name, _varArgs );

	va_end( _varArgs );

	return true;
}		/* -----  end of function mh_dev_set_properties  ----- */
/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_create_playlist
 *  Description:  
 * =====================================================================================
 */
MHPlaylist * mh_dev_create_playlist( MHDev * self )
{
	g_return_val_if_fail( MH_IS_DEV( self ), NULL );

	if( MH_DEV_GET_CLASS( self )->create_playlist != NULL )
	{
		return MH_DEV_GET_CLASS( self )->create_playlist( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::create_playlist()'",
				G_OBJECT_TYPE_NAME( self ));
	}

	return NULL;
}		/* -----  end of function mh_dev_create_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_register_detach_listener
 *  Description:  
 * =====================================================================================
 */
uint32_t mh_dev_register_detach_listener( MHDev * self, MHDevDetachListener * listener)
{
	g_return_val_if_fail( MH_IS_DEV( self), MH_INVALID_PARAM);
	g_return_val_if_fail( listener->callback != NULL, MH_INVALID_PARAM );
	if( MH_DEV_GET_CLASS( self )->register_detach_listener != NULL )
	{
		return MH_DEV_GET_CLASS( self )->register_detach_listener( self, listener);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::register_detach_listener()'",
				G_OBJECT_TYPE_NAME( self ));
	}


	return 0;

}		/* -----  end of function mh_dev_register_detach_listener  ----- */


/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_get_root
 *  Description:  
 * =====================================================================================
 */
MHFolder * mh_dev_get_root(MHDev * self )
{
	g_return_val_if_fail( MH_IS_DEV( self ), NULL );

	if( MH_DEV_GET_CLASS( self )->get_root != NULL )
	{
		return MH_DEV_GET_CLASS( self )->get_root( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::get_root()'",
				G_OBJECT_TYPE_NAME( self ));
	}

	return NULL;
}		/* -----  end of function mh_dev_get_root  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_register_scan_callback
 *  Description:  
 * =====================================================================================
 */
uint32_t mh_dev_register_events_listener( MHDev * self, MHDevEventsListener * listener)
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM );
	g_return_val_if_fail( listener->callback != NULL, MH_INVALID_PARAM );

	if( MH_DEV_GET_CLASS( self )->register_events_listener != NULL )
	{
		return MH_DEV_GET_CLASS( self )->register_events_listener( self, listener );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::register_events_listener()'",
				G_OBJECT_TYPE_NAME( self ));
	}
	return 0;
}		/* -----  end of static function mh_dev_register_scan_callback  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_seek
 *  Description:
 * =====================================================================================
 */
void mh_dev_seek( MHDev * self, MHPb * pb, uint32_t second )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->seek != NULL )
	{
		MH_DEV_GET_CLASS( self )->seek( self, pb, second );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::seek()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_seek  ----- */

///* 
// * ===  FUNCTION  ======================================================================
// *         Name:  mh_dev_save_playlist
// *  Description:  
// * =====================================================================================
// */
//MHResult mh_dev_save_playlist( MHDev * self, MHPlaylist * playlist, gint64 playlist_id  )
//{
//	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARA );
//	g_return_val_if_fail( MH_IS_PLAYLIST( playlist ), MH_INVALID_PARA );
//	g_return_val_if_fail( playlist_id != 0, MH_INVALID_PARA );
//
//	if( MH_DEV_GET_CLASS( self )->save_playlist != NULL )
//	{
//		return MH_DEV_GET_CLASS( self )->save_playlist( self, playlist, playlist_id );
//	}
//	else
//	{
//		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::save_playlist()'",
//				G_OBJECT_TYPE_NAME( self ));
//
//		return MH_FUNC_NOT_IMPLEMENT;
//	}
//}		/* -----  end of function mh_dev_save_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_restore_playlist
 *  Description:  
 * =====================================================================================
 */
MHPlaylist * mh_dev_restore_playlist( MHDev * self, int64_t playlist_id )
{
	g_return_val_if_fail( MH_IS_DEV( self ), NULL );
	g_return_val_if_fail( playlist_id != 0, NULL );

	if( MH_DEV_GET_CLASS( self )->restore_playlist != NULL )
	{
		return MH_DEV_GET_CLASS( self )->restore_playlist( self, playlist_id );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::save_playlist()'",
				G_OBJECT_TYPE_NAME( self ));

		return NULL;
	}
}		/* -----  end of function mh_dev_restore_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_playlist_change
 *  Description:  
 * =====================================================================================
 */
void mh_dev_playlist_change( MHDev * self, MHPb * pb, MHPlaylist * playlist )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->playlist_change != NULL )
	{
		MH_DEV_GET_CLASS( self )->playlist_change( self, pb, playlist );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::playlist_change()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_playlist_change  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_resize
 *  Description:
 * =====================================================================================
 */
void mh_dev_resize( MHDev * self, MHPb * pb, uint32_t offsetx, uint32_t offsety, uint32_t width, uint32_t height )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->resize != NULL )
	{
		MH_DEV_GET_CLASS( self )->resize( self, pb, offsetx, offsety, width, height );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::resize()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_resize  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_pixel_aspect_ratio
 *  Description:
 * =====================================================================================
 */
void mh_dev_pixel_aspect_ratio( MHDev * self, MHPb * pb, uint32_t pixel_n, uint32_t pixel_d )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->pixel_aspect_ratio != NULL )
	{
		MH_DEV_GET_CLASS( self )->pixel_aspect_ratio( self, pb, pixel_n, pixel_d );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::pixel_aspect_ratio()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_pixel_aspect_ratio  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_video_sink
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_video_sink( MHDev * self, MHPb * pb, const char * video_sink_name )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_video_sink != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_video_sink( self, pb, video_sink_name );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_video_sink()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_video_sink  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_media_info
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_media_info( MHDev * self, MHPb * pb, guint type, void * user_data )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_media_info != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_media_info( self, pb, type, user_data );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_media_info()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_media_info  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_get_playlist_info
 *  Description:  
 * =====================================================================================
 */
MHPlaylistInfo * mh_dev_get_playlist_info( MHDev * self)
{
	g_return_val_if_fail( MH_IS_DEV( self ), NULL );
	
	MHPlaylistInfo * _res	=	NULL;
	if( MH_DEV_GET_CLASS( self )->get_playlist_info != NULL )
	{
		_res	=	 MH_DEV_GET_CLASS( self )->get_playlist_info( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::get_playlist_info()'",
				G_OBJECT_TYPE_NAME( self ));
	}

	return _res;
}		/* -----  end of function mh_dev_get_playlist_info  ----- */



/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_create_empty_playlist
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_save_playlist( MHDev * self, const char * name, MHPlaylist * playlist)
{
	g_return_val_if_fail( MH_IS_DEV( self ) && MH_IS_PLAYLIST( playlist ), MH_INVALID_PARAM );

	MHResult _res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->save_playlist != NULL )
	{
		MH_DEV_GET_CLASS( self )->save_playlist( self, name, playlist);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::save_playlist()'",
				G_OBJECT_TYPE_NAME( self ));
		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_create_empty_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_update_playlist
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_update_playlist( MHDev * self, const char * name, MHPlaylist * playlist, int64_t playlist_id)
{
	g_return_val_if_fail( MH_IS_DEV( self ) && MH_IS_PLAYLIST( playlist ) && (playlist_id != 0), MH_INVALID_PARAM);

	MHResult _res	=	MH_OK;
	
	if( MH_DEV_GET_CLASS( self )->update_playlist != NULL )
	{
		MH_DEV_GET_CLASS( self )->update_playlist( self, name, playlist, playlist_id);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::update_playlist()'",
				G_OBJECT_TYPE_NAME( self ));

		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_update_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_delete_playlist
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_delete_playlist( MHDev * self, gint64 playlist_id)
{
	g_return_val_if_fail( MH_IS_DEV( self ) && (playlist_id != 0), MH_INVALID_PARAM );

	MHResult _res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->delete_playlist != NULL )
	{
		MH_DEV_GET_CLASS( self )->delete_playlist( self, playlist_id);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::delete_playlist()'",
				G_OBJECT_TYPE_NAME( self ));

		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_delete_playlist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_get_radiolist
 *  Description:  
 * =====================================================================================
 */
char ** mh_dev_get_radiolist( MHDev * self, int * count)
{
	char **  _res	=	NULL;
	if( MH_DEV_GET_CLASS( self )->get_radiolist != NULL )
	{
		_res	=	MH_DEV_GET_CLASS( self )->get_radiolist(self, count);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'mh_dev_get_radiolist()'",
				G_OBJECT_TYPE_NAME( self ));
	}
	return _res;
}		/* -----  end of function mh_dev_get_radiolist  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_attach_pb
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_attach_pb( MHDev * self, MHPb * pb )
{
	g_return_val_if_fail( MH_IS_DEV( self ) && MH_IS_PB( pb ), MH_INVALID_PARAM);

	MHResult _res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->attach_pb != NULL )
	{
		MH_DEV_GET_CLASS( self )->attach_pb( self, pb );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::attach_pb()'",
				G_OBJECT_TYPE_NAME( self ));
		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_attach_pb  ----- */
/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_signal_emit_by_name
 *  Description:  
 * =====================================================================================
 */
void mh_dev_signal_emit_by_name( MHDev * self, const char * signal_name,...)
{
	g_return_if_fail( MH_IS_DEV( self ) );

	va_list _ap;

	va_start( _ap, signal_name);
	
	if( MH_DEV_GET_CLASS( self )->signal_emit_by_name != NULL)
	{
		MH_DEV_GET_CLASS( self )->signal_emit_by_name( MH_DEV( self ), signal_name, _ap);
	}

	
}		/* -----  end of function mh_dev_signal_emit_by_name  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_scan_abort
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_scan_abort( MHDev * self )
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM);

	MHResult _res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->scan_abort != NULL )
	{
		MH_DEV_GET_CLASS( self )->scan_abort( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::scan_abort()'",
				G_OBJECT_TYPE_NAME( self ));

		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_scan_abort  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_request_app_launch
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_request_app_launch( MHDev * self, const char * app_bundle_id )
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM );

	if( MH_DEV_GET_CLASS( self )->request_app_launch != NULL )
	{
		return MH_DEV_GET_CLASS( self )->request_app_launch( self, app_bundle_id );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::request_app_launch()'",
				G_OBJECT_TYPE_NAME( self ));

		return MH_FUNC_NOT_IMPLEMENT;
	}
}		/* -----  end of function mh_dev_request_app_launch  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_write_location_data
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_write_location_data( MHDev * self, const char * data )
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM );

	if( MH_DEV_GET_CLASS( self )->write_location_data != NULL )
	{
		return MH_DEV_GET_CLASS( self )->write_location_data( self, data );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::write_location_data()'",
				G_OBJECT_TYPE_NAME( self ));

		return MH_FUNC_NOT_IMPLEMENT;
	}
}		/* -----  end of function mh_dev_write_location_data  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_send_vehicle_status
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_send_vehicle_status( MHDev * self, uint32_t remainingRange, int32_t outsideTempreture, int32_t rangeWarning ) 
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM );

	if( MH_DEV_GET_CLASS( self )->send_vehicle_status != NULL )
	{
		return MH_DEV_GET_CLASS( self )->send_vehicle_status( self, remainingRange, outsideTempreture, rangeWarning );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::send_vehicle_status()'",
				G_OBJECT_TYPE_NAME( self ));

		return MH_FUNC_NOT_IMPLEMENT;
	}
}		/* -----  end of function mh_dev_send_vehicle_status  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_write_ea_data
 *  Description:  
 * =====================================================================================
 */
int32_t mh_dev_write_ea_data( MHDev * self, const uint8_t * buf, int32_t len )
{
	g_return_val_if_fail( MH_IS_DEV( self ), -1 );

	if( MH_DEV_GET_CLASS( self )->write_ea_data != NULL )
	{
		return MH_DEV_GET_CLASS( self )->write_ea_data( self, buf, len );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::write_ea_data()'",
				G_OBJECT_TYPE_NAME( self ));

		return -1;
	}
}		/* -----  end of function mh_dev_write_ea_data  ----- */
/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_write_ea_native_data
 *  Description:  
 * =====================================================================================
 */
int32_t mh_dev_write_ea_native_data( MHDev * self, const uint8_t * buf, int32_t len )
{
	g_return_val_if_fail( MH_IS_DEV( self ), -1 );

	if( MH_DEV_GET_CLASS( self )->write_ea_native_data != NULL )
	{
		return MH_DEV_GET_CLASS( self )->write_ea_native_data( self, buf, len );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::write_ea_native_data()'",
				G_OBJECT_TYPE_NAME( self ));

		return -1;
	}
}		/* -----  end of function mh_dev_write_ea_data  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_write_bt_data
 *  Description:  
 * =====================================================================================
 */
int32_t mh_dev_write_bt_data( MHDev * self, const uint8_t * buf, int32_t len )
{
	g_return_val_if_fail( MH_IS_DEV( self ), -1 );

	if( MH_DEV_GET_CLASS( self )->write_bt_data != NULL )
	{
		return MH_DEV_GET_CLASS( self )->write_bt_data( self, buf, len );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::write_bt_data()'",
				G_OBJECT_TYPE_NAME( self ));

		return -1;
	}
}		/* -----  end of function mh_dev_write_bt_data  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_get_item_by_uri
 *  Description:  
 * =====================================================================================
 */
MHItem * mh_dev_get_item_by_uri( MHDev * self, const char * uri)
{
	g_return_val_if_fail( MH_IS_DEV( self ), NULL);
	g_return_val_if_fail( uri != NULL, NULL);

	if( MH_DEV_GET_CLASS( self )->get_item_by_uri != NULL )
	{
		return MH_DEV_GET_CLASS( self )->get_item_by_uri( self, uri );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::get_item_by_uri()'",
				G_OBJECT_TYPE_NAME( self ));

		return NULL;
	}
}		/* -----  end of function mh_dev_get_item_by_uri  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_create_empty_playlist
 *  Description:  
 * =====================================================================================
 */
MHPlaylist * mh_dev_create_empty_playlist( MHDev * self)
{
	g_return_val_if_fail( MH_IS_DEV( self ), NULL);

	if( MH_DEV_GET_CLASS( self )->create_empty_playlist != NULL )
	{
		return MH_DEV_GET_CLASS( self )->create_empty_playlist( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::create_empty_playlist()'",
				G_OBJECT_TYPE_NAME( self ));

		return NULL;
	}
}		/* -----  end of function mh_dev_create_empty_playlist  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_set_pipeline_status
 *  Description:
 * =====================================================================================
 */
void mh_dev_set_pipeline_status( MHDev * self, MHPb * pb, uint32_t status )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->set_pipeline_status != NULL )
	{
		MH_DEV_GET_CLASS( self )->set_pipeline_status( self, pb, status );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::set_pipeline_status()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_set_pipeline_status  ----- */

/*
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_audiobook_playback_speed
 *  Description:
 * =====================================================================================
 */
void mh_dev_audiobook_playback_speed( MHDev * self, MHPb * pb, uint32_t speed )
{
	g_return_if_fail( MH_IS_DEV( self ));

	if( MH_DEV_GET_CLASS( self )->audiobook_playback_speed != NULL )
	{
		MH_DEV_GET_CLASS( self )->audiobook_playback_speed( self, pb, speed );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::audiobook_playback_speed()'",
				G_OBJECT_TYPE_NAME( self ));
	}
}		/* -----  end of function mh_dev_audiobook_playback_speed  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_send_signal_touch
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_send_signal_touch( MHDev * self, MHTouchType press, int x, int y )
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM);

	MHResult	_res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->send_signal_touch != NULL )
	{
		MH_DEV_GET_CLASS( self )->send_signal_touch( self, press, x, y );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::send_signal_touch()'",
				G_OBJECT_TYPE_NAME( self ));
		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;

}		/* -----  end of function mh_dev_send_signal_touch  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_start
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_start(MHDev * self)
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM);

	MHResult	_res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->start != NULL )
	{
		MH_DEV_GET_CLASS( self )->start( self );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::send_signal_touch()'",
				G_OBJECT_TYPE_NAME( self ));
		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_start  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_register_status_listener
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_register_status_listener( MHDev * self, MHDevStatusListener * listener)
{
	g_return_val_if_fail( MH_IS_DEV( self ) && (listener !=	NULL), MH_INVALID_PARAM);

	MHResult	_res	=	MH_OK;
	if( MH_DEV_GET_CLASS( self )->register_status_listener != NULL )
	{
		MH_DEV_GET_CLASS( self )->register_status_listener( self, listener );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::register_status_listener()'",
				G_OBJECT_TYPE_NAME( self ));
		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of static function mh_dev_register_status_listener  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_add_file
 *  Description:  
 * =====================================================================================
 */
MHItem * mh_dev_add_file(MHDev * dest_dev, MHFolder * dest, MHItem * source)
{
	g_return_val_if_fail( MH_IS_DEV( dest_dev ), NULL);
	MHItem * _res;

	if( MH_DEV_GET_CLASS( dest_dev )->add_file != NULL )
	{
		_res	=	MH_DEV_GET_CLASS( dest_dev )->add_file( dest_dev, dest, source );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::add_file()'",
				G_OBJECT_TYPE_NAME( dest_dev ));
	}
	return _res;

}		/* -----  end of function mh_dev_add_file  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_delete_file
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_delete_file( MHDev * dev, MHItem * item)
{
	g_return_val_if_fail( MH_IS_DEV( dev) && MH_IS_ITEM( item),MH_INVALID_PARAM);
	MHResult	_res	=	MH_OK;
	if( MH_DEV_GET_CLASS( dev )->delete_file != NULL)
	{
		_res	=	MH_DEV_GET_CLASS( dev )->delete_file( dev, item);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::delete_file()'",
				G_OBJECT_TYPE_NAME( dev ));
		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_delete_file  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_register_module_status
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_register_module_status( MHDev * dev, ModuleStatusListener * listener)
{
	g_return_val_if_fail( MH_IS_DEV( dev) && listener,MH_INVALID_PARAM);
	g_return_val_if_fail( listener->callback != NULL, MH_INVALID_PARAM );
	MHResult	_res	=	MH_OK;
	if( MH_DEV_GET_CLASS( dev )->register_module_status != NULL)
	{
		_res	=	MH_DEV_GET_CLASS( dev )->register_module_status( dev, listener);
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::register_module_status()'",
				G_OBJECT_TYPE_NAME( dev ));
		_res	=	MH_FUNC_NOT_IMPLEMENT;
	}
	return _res;
}		/* -----  end of function mh_dev_register_module_status  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_send_wifi_conf_info
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_send_wifi_conf_info( MHDev * self, const uint8_t * ssid, const uint8_t * pass, uint8_t securityType, uint8_t channel ) 
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM);

	MHResult	_res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->send_wifi_conf_info != NULL )
	{
		return MH_DEV_GET_CLASS( self )->send_wifi_conf_info( self, ssid, pass, securityType, channel );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::send_wifi_conf_info()'",
				G_OBJECT_TYPE_NAME( self ));

		return MH_FUNC_NOT_IMPLEMENT;
	}

	return _res;
}		/* -----  end of function mh_dev_send_wifi_conf_info  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_wifi_write_iap2
 *  Description:  
 * =====================================================================================
 */
MHResult mh_dev_wifi_write_iap2( MHDev * self, guint8 * buf, gint len ) 
{
	g_return_val_if_fail( MH_IS_DEV( self ), MH_INVALID_PARAM );

	MHResult	_res	=	MH_OK;

	if( MH_DEV_GET_CLASS( self )->wifi_write_iap2 != NULL )
	{
		return MH_DEV_GET_CLASS( self )->wifi_write_iap2( self, buf, len );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::wifi_write_iap2()'",
				G_OBJECT_TYPE_NAME( self ));

		return MH_FUNC_NOT_IMPLEMENT;
	}

	return _res;
}		/* -----  end of function mh_dev_wifi_write_iap2  ----- */
/* 
 *
 * ===  FUNCTION  ======================================================================
 *         Name:  mh_dev_search_name
 *  Description:  
 * =====================================================================================
 */
MHItem ** mh_dev_search_name( MHDev * self, MHItemType type, char * string, gint * count)
{
	g_return_val_if_fail( MH_IS_DEV( self ), NULL );

	MHItem ** _items	=	NULL;

	if( MH_DEV_GET_CLASS( self )->search_name != NULL )
	{
		_items	=	MH_DEV_GET_CLASS( self )->search_name( self, type, string, count );
	}
	else
	{
		g_warning( "Class '%s' does not implement the pure virtual function 'MHDevClass::search_name()'",
				G_OBJECT_TYPE_NAME( self ));
	}
	return _items;

}		/* -----  end of function mh_dev_search_name  ----- */
